stages:
  - prepare
  - unittest
  - build
  - test
  - deployment

prepare:
  stage: prepare
  script:
    - npm install

unittest:
  stage: unittest
  script:
    - npm run test
    # - npx playwright test 

build:
  stage: build
  only:
    - master
    - dev
  script:
    - pwd
    - export
    - docker login registry.gitlab.com -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
    - docker build -t registry.gitlab.com/itea-tech/itea-oppo/mbt-frontend:${CI_BUILD_REF_NAME} . 
    - docker push registry.gitlab.com/itea-tech/itea-oppo/mbt-frontend:${CI_BUILD_REF_NAME}


test:
  stage: test
  script:
    - npm run test

deployment_dev:
  stage: deployment
  only:
    - dev
  script:
    - cd envs/dev
    - docker login registry.gitlab.com -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
    - docker-compose down --remove-orphans
    - docker-compose up -d

deployment:
  stage: deployment
  only:
    - master
  script:
    - cd envs/production
    - docker login registry.gitlab.com -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
    - docker-compose down --remove-orphans
    - docker-compose up -d
