stages:
  - prepare
  - unittest
  - build
  - test
  - publish  
  - deployment

variables:
  TEST_PORT: 7777 

prepare:
  stage: prepare
  script:
    - npm install
  artifacts:
   paths:
   - node_modules 
  cache:
    untracked: true
    paths:
      - node_modules/

unittest:
  stage: unittest
  script:
    - npm run unittest
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - junit.xml
    reports:
      junit:
        - junit.xml

build:
  stage: build
  script:
    - docker build -t registry.gitlab.com/itea-tech/itea-oppo/mbt-frontend:${CI_BUILD_REF_NAME}_${CI_COMMIT_SHORT_SHA} . 
    - docker ps | grep "0.0.0.0:${TEST_PORT}" | awk '{system("docker kill " $1)}' || true
    - docker run -p ${TEST_PORT}:8080 -d registry.gitlab.com/itea-tech/itea-oppo/mbt-frontend:${CI_BUILD_REF_NAME}_${CI_COMMIT_SHORT_SHA}

functional_test:
  stage: test
  timeout: 10 minutes
  script:
    - |
      while ! curl http://localhost:${TEST_PORT} ; do      
        sleep 1
      done
      sleep 5    
    - npx playwright install
    - npx playwright test
    - allure generate
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - allure-report/

container_publish:
  stage: publish
  only:
    - test
    - dev
    - master
  script:
      - docker login registry.gitlab.com -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
      - docker tag registry.gitlab.com/itea-tech/itea-oppo/mbt-frontend:${CI_BUILD_REF_NAME}_${CI_COMMIT_SHORT_SHA} registry.gitlab.com/itea-tech/itea-oppo/mbt-frontend:${CI_BUILD_REF_NAME}
      - docker push registry.gitlab.com/itea-tech/itea-oppo/mbt-frontend:${CI_BUILD_REF_NAME}

deployment_test:
  stage: deployment
  only:
    - test
  script:
    - cd envs/test
    - docker-compose down --remove-orphans
    - docker-compose up -d

deployment_dev:
  stage: deployment
  only:
    - dev
  script:
    - cd envs/dev
    - docker-compose down --remove-orphans
    - docker-compose up -d

deployment:
  stage: deployment
  only:
    - master
  script:
    - cd envs/production
    - docker-compose down --remove-orphans
    - docker-compose up -d
