// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export { }

declare module '@vue/runtime-core' {
    export interface GlobalComponents {
        ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
        ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
        AButton: typeof import('ant-design-vue/es')['Button']
        ACol: typeof import('ant-design-vue/es')['Col']
        AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
        AImage: typeof import('ant-design-vue/es')['Image']
        AInput: typeof import('ant-design-vue/es')['Input']
        AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
        ALayout: typeof import('ant-design-vue/es')['Layout']
        ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
        ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
        ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
        AMenu: typeof import('ant-design-vue/es')['Menu']
        AModal: typeof import('ant-design-vue/es')['Modal']
        APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
        ARow: typeof import('ant-design-vue/es')['Row']
        ASelect: typeof import('ant-design-vue/es')['Select']
        ATable: typeof import('ant-design-vue/es')['Table']
        ATag: typeof import('ant-design-vue/es')['Tag']
        ATooltip: typeof import('ant-design-vue/es')['Tooltip']
        ATree: typeof import('ant-design-vue/es')['Tree']
        Dialog: typeof import('./src/components/Dialog.vue')['default']
        JsonSchemaForm: typeof import('./src/components/JsonSchemaForm.vue')['default']
        Loading: typeof import('./src/components/Loading.vue')['default']
        MenuPanel: typeof import('./src/components/MenuPanel.vue')['default']
        MovableArea: typeof import('./src/components/MovableArea.vue')['default']
        RouterLink: typeof import('vue-router')['RouterLink']
        RouterView: typeof import('vue-router')['RouterView']
        Scrollbar: typeof import('./src/components/Scrollbar.vue')['default']
        Shadow: typeof import('./src/components/Shadow.vue')['default']
        SplitPanel: typeof import('./src/components/basic/split-panel/index.vue')['default']
        SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
        TitleI18n: typeof import('./src/components/basic/title-i18n/index.vue')['default']
    }
}
