// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CreateRule: typeof import('./src/components/CreateRule.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    DynamicTable: typeof import('./src/components/dynamicTable.vue')['default']
    EchartsModel: typeof import('./src/components/EchartsModel.vue')['default']
    JsonSchemaForm: typeof import('./src/components/JsonSchemaForm.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    MenuPanel: typeof import('./src/components/MenuPanel.vue')['default']
    Metainfo: typeof import('./src/components/metainfo.vue')['default']
    MovableArea: typeof import('./src/components/MovableArea.vue')['default']
    RequestData: typeof import('./src/components/RequestData.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scrollbar: typeof import('./src/components/Scrollbar.vue')['default']
    Shadow: typeof import('./src/components/Shadow.vue')['default']
    SplitPanel: typeof import('./src/components/basic/split-panel/index.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    TemplateTable: typeof import('./src/components/templateTable.vue')['default']
    TitleI18n: typeof import('./src/components/basic/title-i18n/index.vue')['default']
  }
}
